//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusUİ.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusUİ.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Girişi.
        /// </summary>
        internal static string butonkullanıcı {
            get {
                return ResourceManager.GetString("butonkullanıcı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici Girişi.
        /// </summary>
        internal static string butonyönetici {
            get {
                return ResourceManager.GetString("butonyönetici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın Al.
        /// </summary>
        internal static string buttonsatınal {
            get {
                return ResourceManager.GetString("buttonsatınal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        internal static string buttonsil {
            get {
                return ResourceManager.GetString("buttonsil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni .
        /// </summary>
        internal static string buttonyeni {
            get {
                return ResourceManager.GetString("buttonyeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinsiyet :.
        /// </summary>
        internal static string combocinsiyet {
            get {
                return ResourceManager.GetString("combocinsiyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kisişel Bilgiler.
        /// </summary>
        internal static string grup_kişisel {
            get {
                return ResourceManager.GetString("grup_kişisel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sefer İşlemleri.
        /// </summary>
        internal static string grup_seferişlemleri {
            get {
                return ResourceManager.GetString("grup_seferişlemleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMİN BİLET BİLGİLER.
        /// </summary>
        internal static string lbl_adminbilgiler {
            get {
                return ResourceManager.GetString("lbl_adminbilgiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMİN GİRİŞİ.
        /// </summary>
        internal static string lbl_admingirişi {
            get {
                return ResourceManager.GetString("lbl_admingirişi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİLET BİLGİLER.
        /// </summary>
        internal static string lbl_biletbilgiler {
            get {
                return ResourceManager.GetString("lbl_biletbilgiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat :.
        /// </summary>
        internal static string lbl_fiyat {
            get {
                return ResourceManager.GetString("lbl_fiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalkış Noktası : .
        /// </summary>
        internal static string lbl_geliş {
            get {
                return ResourceManager.GetString("lbl_geliş", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varış Noktası :.
        /// </summary>
        internal static string lbl_gidiş {
            get {
                return ResourceManager.GetString("lbl_gidiş", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim : .
        /// </summary>
        internal static string lbl_isim {
            get {
                return ResourceManager.GetString("lbl_isim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt ol !.
        /// </summary>
        internal static string lbl_kayıtol {
            get {
                return ResourceManager.GetString("lbl_kayıtol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koltuk No :.
        /// </summary>
        internal static string lbl_koltukno {
            get {
                return ResourceManager.GetString("lbl_koltukno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı :.
        /// </summary>
        internal static string lbl_kullanıcıadı {
            get {
                return ResourceManager.GetString("lbl_kullanıcıadı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KULLANICI GİRİŞİ.
        /// </summary>
        internal static string lbl_kullanıcıgirişi {
            get {
                return ResourceManager.GetString("lbl_kullanıcıgirişi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KULLANICI KAYIT .
        /// </summary>
        internal static string lbl_kullanıcıkayıt {
            get {
                return ResourceManager.GetString("lbl_kullanıcıkayıt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı T.C. :.
        /// </summary>
        internal static string lbl_kullanıcıtc {
            get {
                return ResourceManager.GetString("lbl_kullanıcıtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saat : .
        /// </summary>
        internal static string lbl_saat {
            get {
                return ResourceManager.GetString("lbl_saat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sefer Adı :.
        /// </summary>
        internal static string lbl_seferadı {
            get {
                return ResourceManager.GetString("lbl_seferadı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sefer Saatleri : .
        /// </summary>
        internal static string lbl_sefersaat {
            get {
                return ResourceManager.GetString("lbl_sefersaat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sefer Tarihleri :.
        /// </summary>
        internal static string lbl_sefertarih {
            get {
                return ResourceManager.GetString("lbl_sefertarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre :.
        /// </summary>
        internal static string lbl_şifre {
            get {
                return ResourceManager.GetString("lbl_şifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Tekrar.
        /// </summary>
        internal static string lbl_şifretekrar {
            get {
                return ResourceManager.GetString("lbl_şifretekrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyisim :.
        /// </summary>
        internal static string lbl_soyisim {
            get {
                return ResourceManager.GetString("lbl_soyisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih :.
        /// </summary>
        internal static string lbl_tarih {
            get {
                return ResourceManager.GetString("lbl_tarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.C. Kimlik :.
        /// </summary>
        internal static string lbl_tc {
            get {
                return ResourceManager.GetString("lbl_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon :.
        /// </summary>
        internal static string lbl_tel {
            get {
                return ResourceManager.GetString("lbl_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilet Satın Al .
        /// </summary>
        internal static string menü_biletsatınal {
            get {
                return ResourceManager.GetString("menü_biletsatınal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        internal static string menü_dil {
            get {
                return ResourceManager.GetString("menü_dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sefer Ekle.
        /// </summary>
        internal static string menü_seferekle {
            get {
                return ResourceManager.GetString("menü_seferekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Biletleri Görüntüle.
        /// </summary>
        internal static string menü_tümbiletler {
            get {
                return ResourceManager.GetString("menü_tümbiletler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Biletlerim.
        /// </summary>
        internal static string menü_tümbiletlerim {
            get {
                return ResourceManager.GetString("menü_tümbiletlerim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Kullanıcıları Görüntüle.
        /// </summary>
        internal static string menü_tümkullanıcılar {
            get {
                return ResourceManager.GetString("menü_tümkullanıcılar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİLGİLENDİRME !.
        /// </summary>
        internal static string mesajbilgi {
            get {
                return ResourceManager.GetString("mesajbilgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boş alanları doldurunuz !.
        /// </summary>
        internal static string mesajboş {
            get {
                return ResourceManager.GetString("mesajboş", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emin misin ?.
        /// </summary>
        internal static string mesajemin {
            get {
                return ResourceManager.GetString("mesajemin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı Giriş !.
        /// </summary>
        internal static string mesajgiriş {
            get {
                return ResourceManager.GetString("mesajgiriş", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatalı Giriş !.
        /// </summary>
        internal static string mesajhatalıgiriş {
            get {
                return ResourceManager.GetString("mesajhatalıgiriş", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Yapıldı !.
        /// </summary>
        internal static string mesajkayıt {
            get {
                return ResourceManager.GetString("mesajkayıt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu koltuk dolu !.
        /// </summary>
        internal static string mesajkoltuk {
            get {
                return ResourceManager.GetString("mesajkoltuk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen koltuk seçiniz !.
        /// </summary>
        internal static string mesajkoltukseç {
            get {
                return ResourceManager.GetString("mesajkoltukseç", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim Eklendi !.
        /// </summary>
        internal static string mesajresim {
            get {
                return ResourceManager.GetString("mesajresim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreler Eşleşmiyor !.
        /// </summary>
        internal static string mesajşifre {
            get {
                return ResourceManager.GetString("mesajşifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Silindi !.
        /// </summary>
        internal static string mesajsil {
            get {
                return ResourceManager.GetString("mesajsil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu TC Numara ile daha önce kayıt yapılmış.
        /// </summary>
        internal static string mesajtcvar {
            get {
                return ResourceManager.GetString("mesajtcvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UYARI !!!.
        /// </summary>
        internal static string mesajuyarı {
            get {
                return ResourceManager.GetString("mesajuyarı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yardım.
        /// </summary>
        internal static string yardım {
            get {
                return ResourceManager.GetString("yardım", resourceCulture);
            }
        }
    }
}
